= Deploying f8toggle services on Minishift

== Pre-requisites
* Install https://docs.openshift.org/latest/minishift/getting-started/installing.html[Minishift]
* Install OpenShift command oc
* Start minishift
```
minishift start --memory=7000 --cpus=4 --disk-size=50g
```
on macOS:
```
minishift start --vm-driver=xhyve --memory=7000 --cpus=4 --disk-size=50g
```
* Point `oc` to Minishift
```
oc config use-context minishift
oc login -u developer:developer
```

== Let's deploy `fabric8-toggles` server in OpenShift

Our ` fabric8-toggles` server needs a postgres database and a nodejs server.
We're going to deploy our server in dev mode using minishift.

Let's start with...

=== Deploy database

We're going to deploy  a postgres database using a template that fetch an already built image for you.

Once you have installed `minishift` and `oc`, run the following commands to create all deployments, replica sets, pods and services in the default namespace:
```
# create project
oc new-project f8toggles
# f8toggle database
oc create -f f8toggle-db-deployment.yml
# f8toggle database service
oc create -f f8toggle-db-service.yml
```

Once all scripts passed, the minishift objects will be available:
```
> oc get all
NAME             REVISION   DESIRED   CURRENT   TRIGGERED BY
dc/f8toggle-db   1          1         1         config
NAME               DESIRED   CURRENT   READY     AGE
rc/f8toggle-db-1   1         1         1         16s
NAME              CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
svc/f8toggle-db   172.30.5.173   <none>        5432/TCP   8s
NAME                     READY     STATUS    RESTARTS   AGE
po/f8toggle-db-1-0rtkj   1/1       Running   0          14s
```

=== Build the docker image for the JS server

> Note: you can skip this step by pulling an existing image, in fabric8-toggles-deployment.yml change `image: 172.30.1.1:5000/f8toggles/fabric8togglesdocker:latest`
to `image: registry.devshift.net/fabric8-services/fabric8-toggles:latest`

Using the https://medium.com/@xcoulon/tips-for-minikube-minishift-users-including-myself-accessing-the-clusters-docker-deamon-c15032a60b08[the cluster’s Docker deamon], 
we're going to build the docker image and make it available directly inside the minishift local registry. 
Go to the ../../Dockerfile[Dockerfile] folder and type:
```
cd ../..
eval $(minishift docker-env)
docker login -u developer -p $(oc whoami -t) $(minishift openshift registry)
docker build -t fabric8togglesdocker:latest .
docker tag fabric8togglesdocker $(minishift openshift registry)/f8toggles/fabric8togglesdocker
docker push $(minishift openshift registry)/f8toggles/fabric8togglesdocker
```
We will use `fabric8togglesdocker:latest` in our deployment script.
Let's deploy...

=== Deploy the nodejs server

```
# back to .make/.minishift directory
cd .make/.minishift/
# fabric8-toggles (nodejs server) deployment
oc create -f fabric8-toggles-deployment.yml
# fabric8-toggles (nodejs server) service
oc create -f fabric8-toggles-service.yml
# create route to access
oc create -f fabric8-toggles-route.yml 
```

Once the nodejs server is deployed, the data base is bootstrapped by the server.  
You can verify DB schema was created at server start-up:

```
oc rsh f8toggle-db-2-8zrhk
psql -h localhost -d unleashdb -U user
unleashdb=> \dt+
                            List of relations
 Schema |        Name         | Type  | Owner |    Size    | Description 
--------+---------------------+-------+-------+------------+-------------
 public | client_applications | table | user  | 8192 bytes | 
 public | client_instances    | table | user  | 8192 bytes | 
 public | client_metrics      | table | user  | 8192 bytes | 
 public | events              | table | user  | 16 kB      | 
 public | features            | table | user  | 16 kB      | 
 public | migrations          | table | user  | 8192 bytes | 
 public | strategies          | table | user  | 16 kB      | 
(7 rows)
```

Once the route is created, go to f8toggle admin console:

http://fabric8-toggles-f8toggles.<YOUR_IP>.nip.io (as displayed in your minishit console).
where: 
* <YOUR_IP> could be find out by `minishift ip`. (it's also display in the log with the `minishift start`command)
* use developer /developer as username / password

If something goes wrong, to check logs:
```
oc logs -f fabric8-toggles-1-vvtm2
```
where fabric8-toggles-1-vvtm2 is your ephemeral pod id.